# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('target_contact', '0005_auto_20161102_1319'),
        ('target_contact', '0005_auto_20161102_1321'),
    ]

    operations = [
    ]
