# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('target_contact', '0006_merge_20161102_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target_contact',
            name='idTarget_Contact',
        ),
    ]
