# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0004_auto_20161028_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='arti',
            field=models.ManyToManyField(to='articulo.Articulo'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='vende',
            field=models.ManyToManyField(to='vendedor.Vendedor'),
        ),
    ]
