# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0006_merge_20161102_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='idCampanha',
        ),
        migrations.AddField(
            model_name='campanha',
            name='nombreCamapanha',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
