# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0007_auto_20161102_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campanha',
            old_name='nombreCamapanha',
            new_name='nombreCampanha',
        ),
    ]
