# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0008_auto_20161110_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='porcentajeCampanha',
            field=models.IntegerField(null=True),
        ),
    ]
