# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userlog', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('access_type', models.CharField(max_length=15)),
                ('parameters', models.TextField()),
                ('ip', models.CharField(max_length=25)),
            ],
        ),
    ]
