# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0006_auto_20161102_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombreArticulo',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
