# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulo', '0007_auto_20161110_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArticulo',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombreArticulo', models.CharField(max_length=45, null=True)),
                ('tipoArticulo', models.CharField(max_length=80, null=True)),
                ('montoArticulo', models.IntegerField()),
                ('disponibilidad', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical articulo',
            },
        ),
    ]
