# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0004_auto_20161031_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='idVendedor',
        ),
    ]
